name: Lint and Test Java

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    container:
      image: maven:3.9-eclipse-temurin-17-alpine
    steps:
      - uses: actions/checkout@v4
        with:
          repository: vincev20/lint-test-container
          ref: v1.0.0

      - name: Run style check and tests with coverage
        run: |
          mvn -B clean compile com.spotify.fmt:fmt-maven-plugin:check
          mvn -B clean verify
      
      - name: Prepare artifacts directory
        run: |
          mkdir -p staging
          cp target/*.jar staging/ || echo "No JARs found"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: java-build-artifacts
          path: staging
